// src/lib/footer/Footer.svelte
<script >
  const currentYear = new Date().getFullYear();
</script>

<footer class="w-full px-5 lg:px-20 py-8 style--nested-copy">
  <ul class="flex items-center justify-between">
    <li>
      <p class="text-xs text-gray-500 font-semibold uppercase">
        Copyright <span>{currentYear}</span> rskm.nl
      </p>
    </li>

    <li><a href="https://github.com/aproskam" target="_blank">Github</a></li>

    <li>
      <a href="https://twitter.com/doedatnouniet" target="_blank">Twitter</a>
    </li>
  </ul>
</footer>

// components/footer.vue
<template>
  <footer class="w-full px-5 lg:px-20 py-8 style--nested-copy">
    <ul class="flex items-center justify-between">
      <li>
        <p class="text-xs text-gray-500 font-semibold uppercase">
          Copyright <span>{{ currentYear }}</span> rskm.nl
        </p>
      </li>

      <li><a href="https://github.com/aproskam" target="_blank">Github</a></li>

      <li>
        <a href="https://twitter.com/doedatnouniet" target="_blank">Twitter</a>
      </li>
    </ul>
  </footer>
</template>

<script>
export default {
  data() {
    return {
      currentYear: '',
    }
  },

  created() {
    this.currentYear = new Date().getFullYear()
  },
}
</script>
